version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    semseg_vaihingen:
      image: deephdc/deep-oc-semseg_vaihingen
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    semseg_vaihingen-gpu:
      image: deephdc/deep-oc-semseg_vaihingen:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    semseg_vaihingen-rclone:
      extends:
        service: semseg_vaihingen
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
